export const destinations = [
  { label: 'Amsterdam', value: 'Amsterdam' },
  { label: 'Athens', value: 'Athens' },
  { label: 'Auckland', value: 'Auckland' },
  { label: 'Bali', value: 'Bali' },
  { label: 'Bangkok', value: 'Bangkok' },
  { label: 'Barcelona', value: 'Barcelona' },
  { label: 'Beijing', value: 'Beijing' },
  { label: 'Berlin', value: 'Berlin' },
  { label: 'Bogota', value: 'Bogota' },
  { label: 'Boston', value: 'Boston' },
  { label: 'Brasilia', value: 'Brasilia' },
  { label: 'Brisbane', value: 'Brisbane' },
  { label: 'Brussels', value: 'Brussels' },
  { label: 'Budapest', value: 'Budapest' },
  { label: 'Buenos Aires', value: 'Buenos Aires' },
  { label: 'Cairo', value: 'Cairo' },
  { label: 'Cancun', value: 'Cancun' },
  { label: 'Capetown', value: 'Capetown' },
  { label: 'Casablanca', value: 'Casablanca' },
  { label: 'Chicago', value: 'Chicago' },
  { label: 'Christchurch', value: 'Christchurch' },
  { label: 'Copenhagen', value: 'Copenhagen' },
  { label: 'Cusco', value: 'Cusco' },
  { label: 'Dallas', value: 'Dallas' },
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Denpasar', value: 'Denpasar' },
  { label: 'Dubai', value: 'Dubai' },
  { label: 'Dublin', value: 'Dublin' },
  { label: 'Edinburgh', value: 'Edinburgh' },
  { label: 'Florence', value: 'Florence' },
  { label: 'Frankfurt', value: 'Frankfurt' },
  { label: 'Geneva', value: 'Geneva' },
  { label: 'Granada', value: 'Granada' },
  { label: 'Guangzhou', value: 'Guangzhou' },
  { label: 'Hanoi', value: 'Hanoi' },
  { label: 'Havana', value: 'Havana' },
  { label: 'Helsinki', value: 'Helsinki' },
  { label: 'Ho Chi Minh City', value: 'Ho Chi Minh City' },
  { label: 'Hong Kong', value: 'Hong Kong' },
  { label: 'Honolulu', value: 'Honolulu' },
  { label: 'Istanbul', value: 'Istanbul' },
  { label: 'Jakarta', value: 'Jakarta' },
  { label: 'Jerusalem', value: 'Jerusalem' },
  { label: 'Johannesburg', value: 'Johannesburg' },
  { label: 'Kuala Lumpur', value: 'Kuala Lumpur' },
  { label: 'Kyoto', value: 'Kyoto' },
  { label: 'Lagos', value: 'Lagos' },
  { label: 'Las Vegas', value: 'Las Vegas' },
  { label: 'Lisbon', value: 'Lisbon' },
  { label: 'London', value: 'London' },
  { label: 'Los Angeles', value: 'Los Angeles' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Lyon', value: 'Lyon' },
  { label: 'Macau', value: 'Macau' },
  { label: 'Madrid', value: 'Madrid' },
  { label: 'Malaga', value: 'Malaga' },
  { label: 'Manila', value: 'Manila' },
  { label: 'Marrakech', value: 'Marrakech' },
  { label: 'Melbourne', value: 'Melbourne' },
  { label: 'Mexico City', value: 'Mexico City' },
  { label: 'Miami', value: 'Miami' },
  { label: 'Milan', value: 'Milan' },
  { label: 'Monaco', value: 'Monaco' },
  { label: 'Montreal', value: 'Montreal' },
  { label: 'Moscow', value: 'Moscow' },
  { label: 'Mumbai', value: 'Mumbai' },
  { label: 'Munich', value: 'Munich' },
  { label: 'Nairobi', value: 'Nairobi' },
  { label: 'Naples', value: 'Naples' },
  { label: 'New Delhi', value: 'New Delhi' },
  { label: 'New Orleans', value: 'New Orleans' },
  { label: 'New York', value: 'New York' },
  { label: 'Nice', value: 'Nice' },
  { label: 'Osaka', value: 'Osaka' },
  { label: 'Oslo', value: 'Oslo' },
  { label: 'Ottawa', value: 'Ottawa' },
  { label: 'Paris', value: 'Paris' },
  { label: 'Perth', value: 'Perth' },
  { label: 'Philadelphia', value: 'Philadelphia' },
  { label: 'Phnom Penh', value: 'Phnom Penh' },
  { label: 'Phuket', value: 'Phuket' },
  { label: 'Prague', value: 'Prague' },
  { label: 'Quebec City', value: 'Quebec City' },
  { label: 'Reykjavik', value: 'Reykjavik' },
  { label: 'Rio de Janeiro', value: 'Rio de Janeiro' },
  { label: 'Rome', value: 'Rome' },
  { label: 'Rotterdam', value: 'Rotterdam' },
  { label: 'Saint Petersburg', value: 'Saint Petersburg' },
  { label: 'San Francisco', value: 'San Francisco' },
  { label: 'Santiago', value: 'Santiago' },
  { label: 'Santorini', value: 'Santorini' },
  { label: 'Sao Paulo', value: 'Sao Paulo' },
  { label: 'Seattle', value: 'Seattle' },
  { label: 'Seoul', value: 'Seoul' },
  { label: 'Shanghai', value: 'Shanghai' },
  { label: 'Siem Reap', value: 'Siem Reap' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Stockholm', value: 'Stockholm' },
  { label: 'Sydney', value: 'Sydney' },
  { label: 'Taipei', value: 'Taipei' },
  { label: 'Tallinn', value: 'Tallinn' },
  { label: 'Tbilisi', value: 'Tbilisi' },
  { label: 'Tel Aviv', value: 'Tel Aviv' },
  { label: 'Tokyo', value: 'Tokyo' },
  { label: 'Toronto', value: 'Toronto' },
  { label: 'Vancouver', value: 'Vancouver' },
  { label: 'Venice', value: 'Venice' },
  { label: 'Vienna', value: 'Vienna' },
  { label: 'Warsaw', value: 'Warsaw' },
  { label: 'Washington D.C.', value: 'Washington D.C.' },
  { label: 'Wellington', value: 'Wellington' },
  { label: 'Zagreb', value: 'Zagreb' },
  { label: 'Zurich', value: 'Zurich' }
];
